### ISSUE TITLE
No support for delayed jobs

### ISSUE THREAD

**Issue by teyeheimans** [EdwinHoksberg/beanstalkd-cli#2]
Monitor does not show delayed jobs.

**Comment by EdwinHoksberg** [comment]
Hi, by default the monitor command only shows a few available keys in the output for each tube. To view the number of currently delayed jobs in a tube you can use this command: `beanstalkd-cli monitor --tubekeys=current-jobs-delayed`.

Please check the output of `beanstalkd-cli monitor --help` for more information about the monitor command and [this](https://github.com/beanstalkd/beanstalkd/blob/c17f5030177f689b37ddd6cd2237c96491f6c399/doc/protocol.txt#L499) list of which keys you can use with the `tubekeys` parameter.
