### ISSUE TITLE
No binaries for latest release (1.3.1)

### ISSUE THREAD

**Issue by Nklya** [EdwinHoksberg/beanstalkd-cli#3]
Hello.

I found that there is no binaries for the latest release (1.3.1).
https://github.com/EdwinHoksberg/beanstalkd-cli/releases/tag/1.3.1

But they are available for previous releases, for example, https://github.com/EdwinHoksberg/beanstalkd-cli/releases/tag/1.2.10

**Comment by EdwinHoksberg** [comment]
Thank you for your report! 
It seemed that the Github deploy token was not working anymore, I generated a new one and the binaries are being uploaded again to the new 1.3.2 release.

**Comment by Nklya** [comment]
Thanks 👍
