### ISSUE TITLE
Connection refused when using --server

### ISSUE THREAD

**Issue by squatica** [EdwinHoksberg/beanstalkd-cli#7]
It seems the modifications in 1.4.0 broke the connection, using the prebuilt binary I now receive error "Could not connect to beanstalkd server        error="dial tcp :0: connect: connection refused"

Notice it's trying to connect to tcp empty host and port 0.

Downgrading to version 1.3.2 works fine.

**Comment by lutek** [comment]
the same problem on linux and mac.

**Comment by EdwinHoksberg** [comment]
Thanks for the report! This is fixed with ef20acd and I made a new release: https://github.com/EdwinHoksberg/beanstalkd-cli/releases/latest
